# Dependencies
markdown:         kramdown
highlighter:         pygments
# Permalinks
permalink: none #examples/:title.html
# Server
host:             0.0.0.0
port:             4000
baseurl:          "/bcv"
encoding:         UTF-8
timezone: America/Los_Angeles
