# Dependencies
markdown:         kramdown
# Permalinks
permalink: none #examples/:title.html

highlighter: pygments
# Server
host:             0.0.0.0
port:             4000
baseurl:          "/bcv"
encoding:         UTF-8
timezone: America/Los_Angeles

